# Generated by Django 4.2.9 on 2024-02-02 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_ipv4_address", models.CharField(max_length=30, null=True)),
                ("asset_id", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("tags", models.CharField(max_length=500, null=True)),
                ("acr_override_processing", models.BooleanField(null=True)),
                ("acr_score", models.IntegerField(null=True)),
                ("aes_score", models.IntegerField(null=True)),
                ("display_mac_address", models.CharField(max_length=17, null=True)),
                (
                    "operating_system_asset_list",
                    models.CharField(max_length=100, null=True),
                ),
                ("first_observed", models.DateTimeField(null=True)),
                ("is_licensed", models.BooleanField(null=True)),
                ("is_public", models.BooleanField(null=True)),
                ("last_authenticated_scan_time", models.DateTimeField(null=True)),
                ("last_licensed_scan_time", models.DateTimeField(null=True)),
                ("last_observed", models.DateTimeField(null=True)),
                ("last_scan_time", models.DateTimeField(null=True)),
                ("mac_addresses", models.TextField(null=True)),
                ("mitigations", models.TextField(null=True)),
                ("table_id", models.CharField(max_length=200, null=True)),
                ("types", models.CharField(max_length=4, null=True)),
                ("subscription", models.CharField(max_length=500, null=True)),
                ("OS_Name", models.CharField(max_length=200, null=True)),
                ("owner_group", models.CharField(max_length=100, null=True)),
                ("system_model", models.CharField(max_length=100, null=True)),
                ("environment", models.CharField(max_length=50, null=True)),
                ("date_record_added", models.DateTimeField(null=True)),
                ("device_owner", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("exploitability_ease", models.CharField(max_length=13, null=True)),
                ("exploited_by_malware", models.BooleanField(null=True)),
                ("exploited_by_nessus", models.BooleanField(null=True)),
                ("family", models.CharField(max_length=100, null=True)),
                ("definition_id", models.IntegerField(null=True)),
                ("in_the_news", models.BooleanField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("patch_published", models.DateTimeField(null=True)),
                ("plugin_version", models.FloatField(null=True)),
                ("see_also", models.URLField(null=True)),
                ("solution", models.CharField(max_length=100, null=True)),
                ("unsupported_by_vendor", models.BooleanField(null=True)),
                ("vulnerability_published", models.DateTimeField(null=True)),
                (
                    "cvss2_base_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
                ("cvss2_base_vector", models.CharField(max_length=255, null=True)),
                (
                    "cvss2_temporal_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
                ("cvss2_temporal_vector", models.CharField(max_length=255, null=True)),
                (
                    "cvss3_base_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
                ("cvss3_base_vector", models.CharField(max_length=255, null=True)),
                (
                    "cvss3_temporal_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
                ("cvss3_temporal_vector", models.CharField(max_length=255, null=True)),
                (
                    "vpr_drivers_cvss3_impact_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
                (
                    "vpr_drivers_exploit_code_maturity",
                    models.CharField(max_length=20, null=True),
                ),
                (
                    "vpr_drivers_threat_intensity",
                    models.CharField(max_length=9, null=True),
                ),
                (
                    "vpr_drivers_threat_recency_high",
                    models.SmallIntegerField(null=True),
                ),
                ("vpr_drivers_threat_recency_low", models.SmallIntegerField(null=True)),
                (
                    "vpr_drivers_threat_sources",
                    models.CharField(max_length=30, null=True),
                ),
                (
                    "vpr_score",
                    models.DecimalField(decimal_places=1, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_observed", models.DateTimeField(null=True)),
                ("vulnerability_id", models.CharField(max_length=50, null=True)),
                ("last_seen", models.DateTimeField(null=True)),
                ("output", models.TextField(null=True)),
                ("risk_modified", models.CharField(max_length=4, null=True)),
                ("severity", models.CharField(max_length=8, null=True)),
                ("state", models.CharField(max_length=10, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="database.asset",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="database.definition",
                    ),
                ),
            ],
        ),
    ]
