# Generated by Django 4.2.9 on 2024-02-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="definition_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
