# Generated by Django 4.2.9 on 2024-02-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_definition_definition_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vulnerability_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
